title: andrewmccall.com
email: andrew@andrewmccall.com
description: > # this means to ignore newlines until "baseurl:"
  Andrew is the Cheif Engineer for the Core Big Data team at a large retail bank
   in the UK. All opinions and thoughts on this site are my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andrewmccall
github_username:  andrewmccall

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
